spring:
  application:
    name: beneficiary-service
  ########## DATASOURCE H2
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: "jdbc:h2:mem:beneficiary"
    username: sa
    password: 123qwe
    driverClassName: org.h2.Driver
  ########## JPA H2
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
    properties.hibernate:
      show_sql: false
      format_sql: false